/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bioskop;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author panji
 */
public class FormTiketBioskop extends javax.swing.JFrame {
    javax.swing.table.DefaultTableModel model;
    Tiket tiket;

    /**
     * Creates new form FormTiketBioskopAnyar
     */
    public FormTiketBioskop() {
        initComponents();
        String[] kolom = {"Jenis", "Nama", "Film", "Jam", "Jumlah", "Total"};
        model = new javax.swing.table.DefaultTableModel(null, kolom);
        jTable.setModel(model);
        
        txtOutput.setText(
            "DAFTAR FILM BIOSKOP\n\n" +
            "1. Avengers Endgame        - Rp50.000\n" +
            "2. Spiderman No Way Home   - Rp45.000\n" +
            "3. Fast & Furious 10       - Rp40.000\n" +
            "4. Jurassic World          - Rp42.000\n" +
            "5. Transformer Rise Beast  - Rp47.000\n\n" +
            "Jenis VIP otomatis menambah biaya Rp15.000"
        );
    }
    private void batal() {
        txtNama.setText("");
        txtJumlah.setText("");
        cmbFilm.setSelectedIndex(0);
        cmbJam.setSelectedIndex(0);
        cmbJenisTiket.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        txtJumlah = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        cmbFilm = new javax.swing.JComboBox<>();
        btnCetak = new javax.swing.JButton();
        cmbJenisTiket = new javax.swing.JComboBox<>();
        cmbJam = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        jLabel1.setText("SISTEM PEMESANAN TIKET BIOSKOP");

        jLabel2.setText("NAMA :");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "JENIS", "NAMA", "FILM", "JAM", "JUMLAH", "TOTAL"
            }
        ));
        jScrollPane2.setViewportView(jTable);

        jLabel3.setText("PILIH FILM :");

        jLabel4.setText("JAM TAYANG :");

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel5.setText("JENIS TIKET :");

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel6.setText("JUMLAH TIKET :");

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        cmbFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avengers Endgame", "Spiderman No Way Home", "Fast & Furious 10", "Jurassic World", "Transformer Rise Beast" }));

        btnCetak.setText("CETAK TIKET");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        cmbJenisTiket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "VIP" }));

        cmbJam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "13:00", "16:00", "19:00", "21:00" }));
        cmbJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(215, 215, 215))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbJenisTiket, 0, 200, Short.MAX_VALUE)
                                    .addComponent(txtJumlah)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(cmbJam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama)
                            .addComponent(cmbFilm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClose)
                        .addGap(18, 18, 18)
                        .addComponent(btnCetak)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbJenisTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnBatal)
                    .addComponent(btnClose)
                    .addComponent(btnCetak))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
   if (txtNama.getText().isEmpty() || txtJumlah.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong untuk disimpan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String nama = txtNama.getText();
            String film = cmbFilm.getSelectedItem().toString();
            String jam = cmbJam.getSelectedItem().toString();
            int jumlah = Integer.parseInt(txtJumlah.getText());
            
            // Penentuan harga dasar otomatis sesuai pilihan film
            int harga = 0;
            if (cmbFilm.getSelectedIndex() == 0) harga = 50000;
            else if (cmbFilm.getSelectedIndex() == 1) harga = 45000;
            else if (cmbFilm.getSelectedIndex() == 2) harga = 40000;
            else if (cmbFilm.getSelectedIndex() == 3) harga = 42000;
            else if (cmbFilm.getSelectedIndex() == 4) harga = 47000;

            int totalBayar = 0;
            String jenis = cmbJenisTiket.getSelectedItem().toString();

            if (cmbJenisTiket.getSelectedIndex() == 0) {
                TiketReguler reg = new TiketReguler(nama, film, jam, jumlah, harga);
                totalBayar = reg.hitungTotal();
            } else {
                TiketVIP vip = new TiketVIP(nama, film, jam, jumlah, harga);
                totalBayar = vip.hitungTotal();
            }

            // Memasukkan data ke dalam baris JTable
            DefaultTableModel modelTable = (DefaultTableModel) jTable.getModel();
            modelTable.addRow(new Object[]{jenis, nama, film, jam, jumlah, totalBayar});
            
            batal(); // Bersihkan form setelah disimpan

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Gagal Menyimpan! Pastikan Jumlah diisi menggunakan angka bulat.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
int barisTerpilih = jTable.getSelectedRow();
    if (barisTerpilih >= 0) {
        model.removeRow(barisTerpilih); 
    }     // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
batal();   // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
     if (txtNama.getText().isEmpty() || txtJumlah.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua data inputan harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String nama = txtNama.getText();
            String film = cmbFilm.getSelectedItem().toString();
            String jam = cmbJam.getSelectedItem().toString();
            int jumlah = Integer.parseInt(txtJumlah.getText());
            
            int harga = 0;
            if (cmbFilm.getSelectedIndex() == 0) harga = 50000;
            else if (cmbFilm.getSelectedIndex() == 1) harga = 45000;
            else if (cmbFilm.getSelectedIndex() == 2) harga = 40000;
            else if (cmbFilm.getSelectedIndex() == 3) harga = 42000;
            else if (cmbFilm.getSelectedIndex() == 4) harga = 47000;

            // Penerapan Polimorfisme Runtime
            if (cmbJenisTiket.getSelectedIndex() == 0) {
                tiket = new TiketReguler(nama, film, jam, jumlah, harga);
            } else {
                tiket = new TiketVIP(nama, film, jam, jumlah, harga);
            }

            // Tampilkan output ke JTextArea (Kotak Kanan)
txtOutput.setText("");
txtOutput.append("========= NOTA PEMBELIAN TIKET =========\n");
txtOutput.append("Nama Penonton : " + tiket.getNama() + "\n");
txtOutput.append("Judul Film    : " + tiket.getFilm() + "\n");
txtOutput.append("Jam Tayang    : " + tiket.getJam() + "\n");
txtOutput.append("Jumlah Tiket  : " + tiket.getJumlah() + "\n");
txtOutput.append("Total Bayar   : Rp " + tiket.hitungTotal() + "\n");

// --- BAGIAN BARU DARI IMPLEMENTASI INTERFACE BAB 9 ---
if (tiket instanceof LayananCetak) {
    LayananCetak lc = (LayananCetak) tiket;
    txtOutput.append("Kode Booking  : " + lc.getFormatNotaSingkat() + "\n");
}
if (tiket instanceof FasilitasUtama) {
    FasilitasUtama fu = (FasilitasUtama) tiket;
    txtOutput.append("Sistem Audio  : " + fu.getInfoAudio() + "\n");
}
// -----------------------------------------------------

if (tiket instanceof TiketVIP) {
    txtOutput.append("Fasilitas     : Premium Seat + Free Snack & Drink\n");
} else {
    txtOutput.append("Fasilitas     : Standar Seat\n");
}
txtOutput.append("========================================\n");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Input Jumlah Tiket harus berupa angka bulat!", "Warning", JOptionPane.ERROR_MESSAGE);
        } finally {
            System.out.println("Proses Cetak Tiket Selesai Dieksekusi.");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnCetakActionPerformed

    private void cmbJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTiketBioskop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbFilm;
    private javax.swing.JComboBox<String> cmbJam;
    private javax.swing.JComboBox<String> cmbJenisTiket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
